
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1334, 855)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(52, 296, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stop.setFont(font)
        self.stop.setStyleSheet("color: red")
        self.stop.setObjectName("stop")
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(252, 196, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pause.setFont(font)
        self.pause.setStyleSheet("color: orange")
        self.pause.setObjectName("pause")
        self.off = QtWidgets.QPushButton(self.centralwidget)
        self.off.setGeometry(QtCore.QRect(52, 196, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.off.setFont(font)
        self.off.setStyleSheet("color: blue")
        self.off.setObjectName("off")
        self.rezim = QtWidgets.QPushButton(self.centralwidget)
        self.rezim.setGeometry(QtCore.QRect(52, 126, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rezim.setFont(font)
        self.rezim.setObjectName("rezim")
        self.ox = QtWidgets.QSlider(self.centralwidget)
        self.ox.setGeometry(QtCore.QRect(40, 570, 41, 221))
        self.ox.setOrientation(QtCore.Qt.Vertical)
        self.ox.setObjectName("ox")
        self.oy = QtWidgets.QSlider(self.centralwidget)
        self.oy.setGeometry(QtCore.QRect(115, 569, 21, 221))
        self.oy.setOrientation(QtCore.Qt.Vertical)
        self.oy.setObjectName("oy")
        self.oa = QtWidgets.QSlider(self.centralwidget)
        self.oa.setGeometry(QtCore.QRect(185, 569, 21, 221))
        self.oa.setOrientation(QtCore.Qt.Vertical)
        self.oa.setObjectName("oa")
        self.rx = QtWidgets.QSlider(self.centralwidget)
        self.rx.setGeometry(QtCore.QRect(260, 569, 20, 221))
        self.rx.setOrientation(QtCore.Qt.Vertical)
        self.rx.setObjectName("rx")
        self.ry = QtWidgets.QSlider(self.centralwidget)
        self.ry.setGeometry(QtCore.QRect(330, 569, 20, 221))
        self.ry.setOrientation(QtCore.Qt.Vertical)
        self.ry.setObjectName("ry")
        self.rz = QtWidgets.QSlider(self.centralwidget)
        self.rz.setGeometry(QtCore.QRect(400, 569, 20, 221))
        self.rz.setOrientation(QtCore.Qt.Vertical)
        self.rz.setObjectName("rz")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 520, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 510, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 510, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 510, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 510, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 510, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.indicator = QtWidgets.QLabel(self.centralwidget)
        self.indicator.setGeometry(QtCore.QRect(430, 450, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.indicator.setFont(font)
        self.indicator.setStyleSheet("color: green")
        self.indicator.setObjectName("indicator")
        self.savesistem = QtWidgets.QPushButton(self.centralwidget)
        self.savesistem.setGeometry(QtCore.QRect(522, 306, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.savesistem.setFont(font)
        self.savesistem.setObjectName("savesistem")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(780, 640, 181, 51))
        self.close.setObjectName("close")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 50, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: green")
        self.pushButton_3.setObjectName("pushButton_3")
        self.brak = QtWidgets.QTableWidget(self.centralwidget)
        self.brak.setGeometry(QtCore.QRect(490, 400, 371, 91))
        self.brak.setObjectName("brak")
        self.brak.setColumnCount(3)
        self.brak.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.brak.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.brak.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.brak.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.brak.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.brak.setHorizontalHeaderItem(2, item)
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(780, 570, 181, 51))
        self.open.setObjectName("open")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(522, 36, 731, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1110, 310, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(1060, 540, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 360, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 430, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(1010, 340, 251, 181))
        self.listWidget.setObjectName("listWidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 520, 81, 61))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1334, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop.setText(_translate("MainWindow", "аварийная остановка системы"))
        self.pause.setText(_translate("MainWindow", "пауза"))
        self.off.setText(_translate("MainWindow", "выкл"))
        self.rezim.setText(_translate("MainWindow", "начало работы в ручном режиме"))
        self.label.setText(_translate("MainWindow", "x"))
        self.label_2.setText(_translate("MainWindow", "y"))
        self.label_3.setText(_translate("MainWindow", "z"))
        self.label_4.setText(_translate("MainWindow", "rx"))
        self.label_5.setText(_translate("MainWindow", "ry"))
        self.label_6.setText(_translate("MainWindow", "rz"))
        self.indicator.setText(_translate("MainWindow", "."))
        self.savesistem.setText(_translate("MainWindow", "сохранить состояние системы"))
        self.close.setText(_translate("MainWindow", "закрытие "))
        self.pushButton_3.setText(_translate("MainWindow", "включение системы"))
        item = self.brak.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "обьекты"))
        item = self.brak.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "время"))
        item = self.brak.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.brak.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.brak.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "брак"))
        self.open.setText(_translate("MainWindow", "открытие"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "температура"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "тики"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "радианы"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "градусы"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Actual tool pose"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "квартернионы"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "состояние схвата"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "x"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "y"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "z"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "rx"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ry"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "rz"))
        self.label_7.setText(_translate("MainWindow", "логи"))
        self.save.setText(_translate("MainWindow", "сохранить логи"))
        self.pushButton.setText(_translate("MainWindow", "возвращение на старт"))
        self.pushButton_4.setText(_translate("MainWindow", "move l"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))

    if __name__ == "__main__":
       import sys
       app = QtWidgets.QApplication(sys.argv)
       MainWindow = QtWidgets.QMainWindow()
       ui = Ui_MainWindow()  # <--- ВАЖНО: Проверьте имя класса ниже!
       ui.setupUi(MainWindow)
       MainWindow.show()
       sys.exit(app.exec_())
